//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int Id { get; set; }
        public string LotYear { get; set; }
        public string LotMake { get; set; }
        public string LotModel { get; set; }
        public string LotRunCondition { get; set; }
        public string DamageTypeDescription { get; set; }
        public string CopartFacilityName { get; set; }
        public string SaleTitleState { get; set; }
        public string SaleTitleType { get; set; }
        public string DamageType { get; set; }
        public string LotColor { get; set; }
        public string HasKey { get; set; }
        public string OdometerReading { get; set; }
        public string SalePrice { get; set; }
        public string RepairCost { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
